# 파일 규격 버전
version: "3.8"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services: 
  # 서비스 명
  db:
    # 사용할 이미지
    image: mysql:latest
    # 컨테이너 이름 설정
    container_name: seminar_db_container
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # -e 옵션 
    environment: 
      # 데이터베이스 이름
      - MYSQL_DATABASE=seminar
      # MYSQL 패스워드 설정 옵션
      - MYSQL_ROOT_PASSWORD=seminar
    # 명령어 실행 (한글 인코딩 관련)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql

volumes:
  db: 
    driver: local
