spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seminar?serverTimezone=UTC
    username: root
    password: seminar
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
#      ddl-auto: update
      
auth.jwt:
  issuer: waffle
  jwtSecret: THIS_IS_THE_SECRET_KEY_FOR_THE_WAFFLE_SEMINAR2_ASSIGNMENT_SPRING_PROJECT
  jwtExpiration: 300
#   TODO 누락된 정보를 추가해 주세요.