spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seminar?serverTimezone=UTC
    username: root
    password: seminar
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
      
auth.jwt:
  jwtSecret: n+MbQeThWmZ%DG-@S&#H($@ER2r5u8x/A$B&E(HaPdSgVkYp3s6v9yq4
  jwtExpiration: 864000
  issuer: seminar_issuer
