spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://seminar4.cxiwzzxhzov5.ap-northeast-1.rds.amazonaws.com:3306/seminar?serverTimezone=Asia/Seoul
    username: admin
    password: seminar4
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
      
auth.jwt:
  issuer: root
  jwtSecret: SEMINAR_SECRET_KEY_LONGER_IS_MORE_SECURE
  jwtExpiration: 3600000
server:
  port: 80
